[package]
name = "brutos-multiboot2"
version = "0.1.0"
authors = ["Alistair Geesing <alistair.geesing@icloud.com>"]
edition = "2018"

[features]
default = []
std = []

[dependencies]
brutos-memory = { path = "../memory" }
brutos-util = { path = "../util" }
