[workspace]
members = [
    "alloc",
    "kernel",
    "memory/phys-alloc",
    "memory/slab-alloc",
    "memory/units",
    "memory/vm",
    "multiboot2",
    "platform/pc",
    "sync",
    "task",
    "util",
    "util/macros",
]
