[package]
name = "brutos-memory"
version = "0.1.0"
authors = ["alistair"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brutos-util = { path = "../util" }
